### ISSUE TITLE
Entrega Trabajo Práctico N°1

### ISSUE THREAD

**Issue by matiaspar2000** [matiaspar2000/2020_K2002_Grupo_3#1]
Solicito correción del TP @santiagoferreiros

**Comment by santiagoferreiros** [comment]
@matiaspar2000 @JeroRivero @MartinPetrucci @camilamarinio @DiegoLFrias 

Estimados,

El trabajo práctico está aprobado
Nota: 8

Observaciones
1) No es práctico definir la matriz elemento a elemento. Pueden utilizar las llaves para definir más rápido. Por ejemplo { {1,2} , {5,7} } es una matriz con elementos en la primera fila 1 2 y elmentos en la segunda fila 57
2) Dentro del switch puede utilizar intervalo de valores utilizando los ... puntos suspensivos. Otras alternativa era usar if. Si fuese un conjunto más grande de caracteres se volverían locos.
3) No pide que se imprima por pantalla. Está bien para el testing, pero no para le entrega final. No es parte de la funcionalidad que pide.

Muy muy bien trabajo =D
