### ISSUE TITLE
Entrega Trabajo Práctico N°2

### ISSUE THREAD

**Issue by mpuyol** [matiaspar2000/2020_K2002_Grupo_3#2]
Solicito corrección del Trabajo Practico  @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimado grupo,

El trabajo cumple con la funcionalidad. Pero no implementan ninguna tabla ni matriz de transición. Está toda hecha con un montón de SWITCH CASE. Eso les va a cumplir mucho el trabajo más adelante. 

La entrega se considera aprobada, pero tengan en consideración lo que les estoy mencionado. Está en la consigna la TT, y debe ser implementada de algún modo. Es la forma de organizar la información. 

Saludos,

Nota: 7

@mpuyol  @JeroRivero  @MartinPetrucci  @matiaspar2000
