### ISSUE TITLE
Entrega Trabajo Práctico N°2 v2

### ISSUE THREAD

**Issue by mpuyol** [matiaspar2000/2020_K2002_Grupo_3#3]
Solicito corrección de la segunda entrega del Trabajo Practico  N°2 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Matias,

Vi los cambios. Cada elemento de la tabla debe estar compuesto por dos cosas {ESTADO_Siguiente , CadenaPushPila }

Lo que ustedes hacen funciona perfectamente. Pero la lógica de la tabla de transición la tienen metida dentro del switch con varios case e if. Y solo usan la TT como una guía. Pero no está toda la información. 

Algo así sería la tabla

datoTT tt[posicionCaracter][cantEstado][valorPila]={
     {{{4,"$"},{4,"R"}},{{1,"$"},{1,"R"}},{{4,"$"},{4,"R"}}},    //columna1
     {{{1,"$"},{1,"R"}},{{1,"$"},{1,"R"}},{{5,"$"},{5,"R"}}},    //columna2
     {{{6,"$"},{6,"R"}},{{0,"$"},{0,"R"}},{{0,"$"},{0,"R"}}},    //columna3
     {{{0,"R$"},{0,"RR"}},{{7,"$"},{7,"R"}},{{7,"$"},{7,"R"}}},  //columna4
     {{{8,"$"},{8,"R"}},{{8,"$"},{2,"Ɛ"}},{{8,"$"},{2,"Ɛ"}}},    //columna5
     {{{3,"$"},{3,"R"}},{{3,"$"},{3,"R"}},{{3,"$"},{3,"R"}}},    //columna6   
};

Entonces, con acceder al elemento ya tienen toda la información
A qué estado deben ir
Qué deben pushear en la pila

De todos modos,
Mejoro su nota es un 8

Saludos =)

No hace falta que hagan reentrega. Ya hicieron suficiente trabajo estimados. 
Valoro mucho su compromiso. Es simplemente una observación para que lo tengan presente. Más que nada para ir viendo la manera de estructurar la información
