### ISSUE TITLE
Entrega Trabajo Práctico N° 4

### ISSUE THREAD

**Issue by matiaspar2000** [matiaspar2000/2020_K2002_Grupo_3#4]
Solicito corrección del trabajo práctico @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimado grupo

![image](https://user-images.githubusercontent.com/46604718/96031424-b2c04c80-0e33-11eb-9852-2bd688eb1902.png)

Están teniendo errores en el archivo de Bison.
Hagan las correcciones y me lo reenvían. Parece que algo quedó mal escrito.
