### ISSUE TITLE
Entrega número 2 Trabajo Práctico N° 4 

### ISSUE THREAD

**Issue by mpuyol** [matiaspar2000/2020_K2002_Grupo_3#5]
Solicitamos corrección del TP @santiagoferreiros
Nota : Tenemos un problema con los caracteres "{"  y  "}"   que no sabemos si el programa los esta leyendo de manera errónea o si el error esta en nuestro desarrollo.

**Comment by santiagoferreiros** [comment]
Estimado grupo

Veo que está funcionando bien

![image](https://user-images.githubusercontent.com/46604718/97059719-94f79380-1567-11eb-989e-c12c72fc2703.png)

Veo que los está leyendo, el léxico los reconoce bien, y los envía al sintáctico, y el sintáctico los toma bien, llega a sentencia compuesta.

No encontré el problema.

Me mandan alguna captura mejor?

Saludos

Santiago

**Comment by matiaspar2000** [comment]
![image](https://user-images.githubusercontent.com/62450031/97083411-2574b900-15e6-11eb-82f9-328aced8237b.png)

El tema no era tanto al probar sino en el código de bison, ahi por ejemplo expPrimaria aparece en blanco como si estuviera adentro de las llaves del código C, cuando sacábamos todo lo de adentro de las llaves se veía como arriba (marcado en color azul como listaArgumentos) y no sabíamos si esto estaba rompiendo algo o no, pero si los toma bien y llega a donde tiene que llegar entonces supongo que solo es un bug visual y no afecta, Muchas gracias

**Comment by santiagoferreiros** [comment]
Matias,

Ya lo respondimos en el meet de hoy.
Es solo algo visual.
Saludos 👍 
Santiago
