### ISSUE TITLE
Corrección TP Integrador 

### ISSUE THREAD

**Issue by mpuyol** [matiaspar2000/2020_K2002_Grupo_3#6]
Solicitamos corrección del TP @santiagoferreiros 
Aclaración: Resolvimos el inconveniente que teníamos reservando memoria para la TS, y hicimos pequeñas mejoras a la gramática.
Ejecutando el programa con el archivo .txt que adjuntamos se genera el reporte sin inconvenientes

**Comment by santiagoferreiros** [comment]
La entrega se encuentra aprobada.
Felicitaciones!
